package com.ivonix.pulse.ontology.eventbus;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import javax.crypto.Mac;
import javax.crypto.spec.SecretKeySpec;
import java.net.InetAddress;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.util.*;

@Service
public class EventBusService {
    private static final int MAX_ATTEMPTS=10,MAX_PAYLOAD_BYTES=1024*1024,MAX_BATCH=100,DEFAULT_LEASE_SECONDS=60;
    private final JdbcTemplate jdbc; private final ObjectMapper mapper; private final byte[] webhookRootKey; private final String workerId; private final int leaseSeconds;
    private final HttpClient http=HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(5)).followRedirects(HttpClient.Redirect.NEVER).build();
    public EventBusService(JdbcTemplate jdbc,ObjectMapper mapper){this.jdbc=jdbc;this.mapper=mapper;String raw=System.getenv("PULSE_MASTER_KEY");if(raw==null||raw.isBlank())throw new IllegalStateException("PULSE_MASTER_KEY is required");try{webhookRootKey=Base64.getDecoder().decode(raw);}catch(Exception e){throw new IllegalStateException("PULSE_MASTER_KEY must be base64",e);}if(webhookRootKey.length!=32)throw new IllegalStateException("PULSE_MASTER_KEY must decode to 32 bytes");workerId=Optional.ofNullable(System.getenv("PULSE_EVENT_WORKER_ID")).filter(s->s.length()>=8&&s.length()<=128).orElseGet(()->"evb-"+UUID.randomUUID());int configured;try{configured=Integer.parseInt(System.getenv().getOrDefault("PULSE_EVENT_LEASE_SECONDS",String.valueOf(DEFAULT_LEASE_SECONDS)));}catch(NumberFormatException e){configured=DEFAULT_LEASE_SECONDS;}leaseSeconds=Math.max(15,Math.min(configured,900));}
    public UUID publish(String type,String source,Map<String,Object> payload,UUID org,String correlationId,UUID userId){requireMember(org,userId);return publishSystem(type,source,payload,org,correlationId,null);}
    public UUID publishSystem(String type,String source,Map<String,Object> payload,UUID org,String correlationId,String externalEventId){
        UUID typeId=jdbc.queryForObject("select id from public.event_types where name=? and event_version=1 and is_active=true",UUID.class,type);
        String payloadJson; Map<String,Object> canonical; UUID id=UUID.randomUUID(); java.time.Instant occurredAt=java.time.Instant.now();
        try{
            Map<String,Object> safePayload=payload==null?Map.of():payload;
            payloadJson=mapper.writeValueAsString(safePayload);
            if(payloadJson.getBytes(StandardCharsets.UTF_8).length>MAX_PAYLOAD_BYTES)throw new IllegalArgumentException("Event payload exceeds 1 MiB");
            canonical=CanonicalPulseEvent.build(mapper,webhookRootKey,type,source,org,correlationId,safePayload,id,occurredAt);
        }catch(JsonProcessingException e){throw new IllegalArgumentException("Invalid event payload",e);}
        String canonicalJson;
        try{canonicalJson=mapper.writeValueAsString(canonical);}catch(JsonProcessingException e){throw new IllegalArgumentException("Invalid canonical event envelope",e);}
        jdbc.update("insert into public.events(id,event_type_id,organization_id,source_service,event_time,payload,canonical_envelope,correlation_id,created_at,version,external_event_id) values (?,?,?,?,?,?::jsonb,?::jsonb,?,now(),1,?)",id,typeId,org,source,occurredAt,payloadJson,canonicalJson,correlationId,externalEventId);
        queueDeliveries(id,typeId,org);return id;
    }
    public List<Map<String,Object>> recent(UUID org,UUID userId,int limit){requireMember(org,userId);int n=Math.max(1,Math.min(limit,200));return jdbc.queryForList("select e.id,e.event_type_id,e.source_service,e.event_time,e.payload,e.canonical_envelope,e.correlation_id,e.version from public.events e where e.organization_id=? order by e.event_time desc limit ?",org,n);}
    public SubscriptionResult subscribe(UUID userId,SubscriptionRequest r){requireMember(r.organizationId(),userId);if(!Set.of("service","user").contains(r.subscriberType()))throw new IllegalArgumentException("Invalid subscriber type");if(r.endpointUrl()!=null)validateEndpoint(r.endpointUrl());UUID id=UUID.randomUUID();try{jdbc.update("insert into public.event_subscriptions(id,organization_id,subscriber_type,subscriber_id,event_type_id,filter,endpoint_url) values (?,?,?,?,?,?,?)",id,r.organizationId(),r.subscriberType(),r.subscriberId(),r.eventTypeId(),r.filter()==null?null:mapper.writeValueAsString(r.filter),r.endpointUrl());}catch(JsonProcessingException e){throw new IllegalArgumentException("Invalid subscription filter",e);}return new SubscriptionResult(id,r.endpointUrl()==null?null:webhookSecret(id));}
    private void queueDeliveries(UUID eventId,UUID typeId,UUID org){jdbc.update("insert into public.event_deliveries(event_id,subscription_id) select ?,id from public.event_subscriptions where organization_id=? and event_type_id=? and active=true on conflict(event_id,subscription_id) do nothing",eventId,org,typeId);}
    public void deliverPending(int batchSize){int n=Math.max(1,Math.min(batchSize,MAX_BATCH));List<Map<String,Object>> rows=jdbc.queryForList("select * from public.claim_event_delivery(?,?)",workerId,leaseSeconds);for(Map<String,Object> r:rows)deliver(r);for(int i=rows.size();i<n;i++){List<Map<String,Object>> next=jdbc.queryForList("select * from public.claim_event_delivery(?,?)",workerId,leaseSeconds);if(next.isEmpty())break;deliver(next.get(0));}}
    private void deliver(Map<String,Object> r){long delivery=((Number)r.get("id")).longValue();String endpoint=(String)r.get("endpoint_url");UUID subscriptionId=(UUID)r.get("subscription_id");UUID eventId=(UUID)r.get("event_id");UUID operationId=(UUID)r.get("operation_id");if(operationId==null)throw new IllegalStateException("Delivery operation_id is required");try{if(endpoint!=null){validateEndpoint(endpoint);Map<String,Object> envelope=new LinkedHashMap<>();envelope.put("id",eventId);envelope.put("operationId",operationId);envelope.put("sourceService",r.get("source_service"));envelope.put("eventTime",r.get("event_time"));envelope.put("payload",r.get("payload"));envelope.put("correlationId",r.get("correlation_id"));String body=mapper.writeValueAsString(envelope);if(body.getBytes(StandardCharsets.UTF_8).length>MAX_PAYLOAD_BYTES)throw new IllegalArgumentException("Webhook payload exceeds 1 MiB");long timestamp=System.currentTimeMillis()/1000;String signature="sha256="+hmacHex(webhookSecret(subscriptionId),timestamp+"."+body);HttpRequest req=HttpRequest.newBuilder(URI.create(endpoint)).timeout(Duration.ofSeconds(10)).header("Content-Type","application/json").header("X-PULSE-Webhook-Version","1").header("X-PULSE-Webhook-Timestamp",Long.toString(timestamp)).header("X-PULSE-Signature",signature).header("X-PULSE-Event-ID",String.valueOf(eventId)).header("Idempotency-Key",operationId.toString()).POST(HttpRequest.BodyPublishers.ofString(body)).build();HttpResponse<Void> resp=http.send(req,HttpResponse.BodyHandlers.discarding());if(resp.statusCode()<200||resp.statusCode()>=300)throw new IllegalStateException("Subscriber HTTP "+resp.statusCode());}int updated=jdbc.update("update public.event_deliveries set status='delivered',attempts=attempts+1,last_attempt_at=now(),delivered_at=now(),completed_at=now(),last_error=null,error_message=null,worker_id=null,lease_until=null where id=? and operation_id=? and worker_id=? and lease_until > now() and status in ('pending','failed')",delivery,operationId,workerId);if(updated!=1)throw new IllegalStateException("Delivery ownership was lost before terminal success");}catch(Exception e){String message=String.valueOf(e.getMessage());jdbc.update("update public.event_deliveries set status=case when attempts+1>=? then 'dead_letter' else 'failed' end,attempts=attempts+1,last_attempt_at=now(),last_error=?,error_message=?,worker_id=null,lease_until=null where id=? and operation_id=? and worker_id=? and lease_until > now() and status in ('pending','failed')",MAX_ATTEMPTS,message.substring(0,Math.min(1000,message.length())),message.substring(0,Math.min(1000,message.length())),delivery,operationId,workerId);}}
    private String webhookSecret(UUID subscriptionId){return Base64.getUrlEncoder().withoutPadding().encodeToString(hmacBytes("pulse-webhook-v1:"+subscriptionId));}
    private byte[] hmacBytes(String value){try{Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(webhookRootKey,"HmacSHA256"));return mac.doFinal(value.getBytes(StandardCharsets.UTF_8));}catch(Exception e){throw new IllegalStateException("Webhook signing unavailable",e);}}
    private String hmacHex(String secret,String value){try{byte[] key=Base64.getUrlDecoder().decode(secret);Mac mac=Mac.getInstance("HmacSHA256");mac.init(new SecretKeySpec(key,"HmacSHA256"));return HexFormat.of().formatHex(mac.doFinal(value.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException("Webhook signing unavailable",e);}}
    private void validateEndpoint(String endpoint){URI uri;try{uri=URI.create(endpoint);}catch(IllegalArgumentException e){throw new IllegalArgumentException("Invalid webhook URL",e);}if(!"https".equalsIgnoreCase(uri.getScheme())||uri.getUserInfo()!=null||uri.getHost()==null)throw new IllegalArgumentException("Webhook URL must be HTTPS with a public hostname");try{for(InetAddress address:InetAddress.getAllByName(uri.getHost()))rejectNonPublic(address);}catch(java.net.UnknownHostException e){throw new IllegalArgumentException("Webhook hostname could not be resolved",e);}}
    private void rejectNonPublic(InetAddress address){if(address.isAnyLocalAddress()||address.isLoopbackAddress()||address.isLinkLocalAddress()||address.isSiteLocalAddress()||address.isMulticastAddress()||isSpecial(address))throw new IllegalArgumentException("Webhook destination is not publicly routable");byte[] b=address.getAddress();if(b.length==16&&isIpv4Mapped(b)){int a=b[12]&255,c=b[13]&255;if(a==127||a==10||a==0||(a==169&&c==254)||(a==172&&c>=16&&c<=31)||(a==192&&c==168))throw new IllegalArgumentException("Webhook destination is not publicly routable");}}
    private boolean isSpecial(InetAddress address){byte[] b=address.getAddress();if(b.length==4){int a=b[0]&255,c=b[1]&255,d=b[2]&255;return a==0||(a==100&&c>=64&&c<=127)||(a==192&&c==0)||(a==198&&(d==18||d==19));}int first=b[0]&255;return first>=0xfc&&first<=0xfd;}
    private boolean isIpv4Mapped(byte[] b){if(b.length!=16)return false;for(int i=0;i<10;i++)if(b[i]!=0)return false;return b[10]==(byte)0xff&&b[11]==(byte)0xff;}
    private void requireMember(UUID org,UUID user){Integer n=jdbc.queryForObject("select count(*) from public.organization_members where organization_id=? and user_id=?",Integer.class,org,user);if(n==null||n<1)throw new SecurityException("Organization membership required");}
    public record SubscriptionRequest(UUID organizationId,String subscriberType,String subscriberId,UUID eventTypeId,Map<String,Object> filter,String endpointUrl){}
    public record SubscriptionResult(UUID subscriptionId,String webhookSecret){}
}
