import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import './styles.css';

const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:8081/api/v1';
async function api(path,options={}){const token=localStorage.getItem('pulse_access_token');const res=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}});if(!res.ok)throw new Error(await res.text()||`HTTP ${res.status}`);return res.status===204?null:res.json();}

function OfflineIndicator(){const [online,setOnline]=useState(navigator.onLine);useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);return <span className={online?'status online':'status offline'}>{online?'ONLINE':'OFFLINE'}</span>}
function FindSearch(){const [text,setText]=useState(''),[results,setResults]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');async function run(){setBusy(true);setError('');try{const serviceId=prompt('FIND service UUID');if(!serviceId)return;const data=await api('/find/searches',{method:'POST',body:JSON.stringify({serviceId,embeddingType:'text',text,query:{text}})});setResults([{id:data,status:'search created'}])}catch(e){setError(e.message)}finally{setBusy(false)}}return <section><h2>PULSE FIND</h2><p>Consent-based reunification search orchestration.</p><input value={text} onChange={e=>setText(e.target.value)} placeholder="Describe the person, pet or vehicle"/><button disabled={!text||busy} onClick={run}>{busy?'Searching…':'Create search'}</button>{error&&<pre>{error}</pre>}<ul>{results.map(r=><li key={r.id}>{r.id} — {r.status}</li>)}</ul></section>}
function OntologyGraph(){const [rows,setRows]=useState([]),[error,setError]=useState('');async function load(){try{const id=prompt('Ontology entity UUID');if(id)setRows(await api(`/ontology/entities/${id}/graph?depth=3`))}catch(e){setError(e.message)}}return <section><h2>PULSE Ontology</h2><p>Graph traversal and PageRank intelligence.</p><button onClick={load}>Load graph</button>{error&&<pre>{error}</pre>}<pre>{JSON.stringify(rows,null,2)}</pre></section>}
function EngineeringDashboard(){const [result,setResult]=useState(null);async function run(){const deviceId=prompt('Device UUID');if(!deviceId)return;const r=await api('/engineering/diagnose',{method:'POST',body:JSON.stringify({deviceId,evidenceIds:[],telemetry:{}})});setResult(r)}return <section><h2>PULSE Engineering</h2><p>Evidence-aware machine diagnostics.</p><button onClick={run}>Run diagnosis</button>{result&&<pre>{JSON.stringify(result,null,2)}</pre>}</section>}
function SecurityDashboard(){const [hash,setHash]=useState(''),[result,setResult]=useState(null);async function scan(){const r=await api('/shield/scan',{method:'POST',body:JSON.stringify({hash})});setResult(r)}return <section><h2>PULSE Shield</h2><p>Security event and threat intelligence controls.</p><input value={hash} onChange={e=>setHash(e.target.value)} placeholder="SHA-256 file hash"/><button onClick={scan} disabled={!hash}>Scan hash</button>{result&&<pre>{JSON.stringify(result,null,2)}</pre>}</section>}
function App(){return <main><header><div><span className="eyebrow">IVONIX</span><h1>PULSE Machine Connect</h1><p>Every machine is a neuron.</p></div><OfflineIndicator/></header><div className="grid"><FindSearch/><OntologyGraph/><EngineeringDashboard/><SecurityDashboard/><section><h2>PULSE Edge</h2><p>Offline-first synchronization is handled by the Edge worker and durable sync queue.</p></section></div></main>}
createRoot(document.getElementById('root')).render(<App/>);
