import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client'; import './styles.css';
const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:8081/api/v1';
async function api(path,options={}){const token=localStorage.getItem('pulse_access_token');const res=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{}) ,...(options.headers||{})}});if(!res.ok)throw new Error(await res.text()||`HTTP ${res.status}`);return res.status===204?null:res.json();}
function OfflineIndicator(){const [online,setOnline]=useState(navigator.onLine);useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on);addEventListener('offline',off);return()=>{removeEventListener('online',on);removeEventListener('offline',off)}},[]);return <span className={online?'status online':'status offline'}>{online?'ONLINE':'OFFLINE'}</span>}
function Panel({title,children}){return <section className="panel"><div className="panel-title"><span className="dot"/><h2>{title}</h2></div>{children}</section>}
function FindSearch(){const [text,setText]=useState(''),[results,setResults]=useState([]),[error,setError]=useState('');async function run(){try{setError('');const serviceId=prompt('FIND service UUID');if(!serviceId)return;const id=await api('/find/searches',{method:'POST',body:JSON.stringify({serviceId,query:{text}})});setResults([{id,status:'search created; submit an embedding to /matches'}])}catch(e){setError(e.message)}}return <Panel title="PULSE FIND"><p>Consent-based reunification for people, pets and vehicles.</p><input value={text} onChange={e=>setText(e.target.value)} placeholder="Search description"/><button disabled={!text} onClick={run}>Create search</button>{error&&<pre>{error}</pre>}{results.map(r=><div className="result" key={r.id}>{r.id}<br/>{r.status}</div>)}</Panel>}
function Ontology(){const [rows,setRows]=useState([]);const [error,setError]=useState('');async function graph(){try{const id=prompt('Ontology entity UUID');if(id)setRows(await api(`/ontology/entities/${id}/graph?depth=3`))}catch(e){setError(e.message)}}async function rank(){try{setRows(await api('/ontology/pagerank?iterations=20'))}catch(e){setError(e.message)}}return <Panel title="PULSE Ontology"><p>Graph traversal and PageRank intelligence.</p><div className="actions"><button onClick={graph}>Load graph</button><button onClick={rank}>Run PageRank</button></div>{error&&<pre>{error}</pre>}<pre>{JSON.stringify(rows,null,2)}</pre></Panel>}
function Engineering(){const [result,setResult]=useState(null);async function run(){try{const deviceId=prompt('Device UUID');if(deviceId)setResult(await api('/engineering/diagnose',{method:'POST',body:JSON.stringify({deviceId,evidenceIds:[],telemetry:{}})}))}catch(e){setResult({error:e.message})}}return <Panel title="PULSE Engineering"><p>Machine DNA, evidence and diagnostic orchestration.</p><button onClick={run}>Run diagnosis</button>{result&&<pre>{JSON.stringify(result,null,2)}</pre>}</Panel>}
function Shield(){const [hash,setHash]=useState(''),[result,setResult]=useState(null);async function scan(){try{setResult(await api('/shield/scan',{method:'POST',body:JSON.stringify({hash})}))}catch(e){setResult({error:e.message})}}return <Panel title="PULSE Shield"><p>Threat intelligence, malware scanning and security response.</p><input value={hash} onChange={e=>setHash(e.target.value)} placeholder="SHA-256 file hash"/><button disabled={!hash} onClick={scan}>Scan hash</button>{result&&<pre>{JSON.stringify(result,null,2)}</pre>}</Panel>}
function Domains(){const domains=['Automotive','Industrial','Robotics','Energy','Electronics','Agriculture','Aviation','Naval','Space'];return <Panel title="Universal Domains"><p>Shared Device + Machine DNA foundation with specialized telemetry adapters.</p><div className="chips">{domains.map(d=><span key={d}>{d}</span>)}</div></Panel>}
function Chrysalis(){return <Panel title="PULSE CHRYSALIS"><p>Legacy assessment and controlled modernization paths.</p><div className="result">POST /api/v1/chrysalis/assess<br/>POST /api/v1/chrysalis/execute</div></Panel>}
function Edge(){return <Panel title="PULSE Edge"><p>SQLite durable queue with retrying cloud synchronization.</p><div className="result">Offline writes are queued locally and synchronized when connectivity returns.</div></Panel>}
function App(){return <main><header><div><span className="eyebrow">IVONIX / PULSE</span><h1>Machine Connect</h1><p>Every machine is a neuron.</p></div><OfflineIndicator/></header><div className="grid"><FindSearch/><Ontology/><Engineering/><Shield/><Domains/><Chrysalis/><Edge/></div></main>}
createRoot(document.getElementById('root')).render(<App/>);