import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client'; import './styles.css';
import DomainDashboard,{DOMAINS} from './components/DomainDashboard'; import ServiceBuilder from './components/ServiceBuilder'; import AiStudio from './components/AiStudio'; import AppForge from './components/AppForge'; import ReportBuilder from './components/ReportBuilder'; import Aegis from './components/Aegis'; import DigitalTwin from './components/DigitalTwin'; import Intelligence from './components/Intelligence'; import CoreMonitor from './components/CoreMonitor'; import LedgerExplorer from './components/LedgerExplorer'; import FounderConsole from './components/FounderConsole'; import KeyActivate from './components/KeyActivate'; import Batch5Panel from './components/Batch5Panel';
const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:8081/api/v1';
async function founderProfile(){const t=localStorage.getItem('pulse_access_token');if(!t)return null;const r=await fetch(API+'/founder/profile',{headers:{Authorization:`Bearer ${t}`}});if(!r.ok)return null;return r.json();}
function OfflineIndicator(){const [online,setOnline]=useState(navigator.onLine);useEffect(()=>{const on=()=>setOnline(true),off=()=>setOnline(false);addEventListener('online',on),addEventListener('offline',off);return()=>{removeEventListener('online',on),removeEventListener('offline',off)}},[]);return <span className={online?'status online':'status offline'}>{online?'ONLINE':'OFFLINE'}</span>}
function Panel({title,children}){return <section className="panel"><div className="panel-title"><span className="dot"/><h2>{title}</h2></div>{children}</section>}
async function api(path,options={}){const t=localStorage.getItem('pulse_access_token');const r=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',...(t?{Authorization:`Bearer ${t}`}:{})}});if(!r.ok)throw Error(await r.text());return r.status===204?null:r.json()}
function FindSearch(){const [text,setText]=useState(''),[results,setResults]=useState([]),[error,setError]=useState('');async function run(){try{setError('');const serviceId=prompt('FIND service UUID');if(!serviceId)return;const id=await api('/find/searches',{method:'POST',body:JSON.stringify({serviceId,query:{text}})});setResults([{id,status:'search created'}])}catch(e){setError(e.message)}}return <Panel title="PULSE FIND"><p>Consent-based reunification for people, pets and vehicles.</p><input value={text} onChange={e=>setText(e.target.value)} placeholder="Search description"/><button disabled={!text} onClick={run}>Create search</button>{error&&<pre className="error">{error}</pre>}{results.map(r=><div className="result" key={r.id}>{r.id}<br/>{r.status}</div>)}</Panel>}
function Ontology(){const [rows,setRows]=useState([]);const [error,setError]=useState('');async function graph(){try{const id=prompt('Ontology entity UUID');if(id)setRows(await api(`/ontology/entities/${id}/graph?depth=3`))}catch(e){setError(e.message)}}async function rank(){try{setRows(await api('/ontology/pagerank?iterations=20'))}catch(e){setError(e.message)}}return <Panel title="PULSE Ontology"><p>Graph traversal and PageRank intelligence.</p><div className="actions"><button onClick={graph}>Load graph</button><button onClick={rank}>Run PageRank</button></div>{error&&<pre className="error">{error}</pre>}<pre>{JSON.stringify(rows,null,2)}</pre></Panel>}
function Engineering(){const [result,setResult]=useState(null);async function run(){try{const deviceId=prompt('Device UUID');if(deviceId){const r=await api('/engineering/diagnose',{method:'POST',body:JSON.stringify({deviceId,evidenceIds:[],telemetry:{}})});setResult(r)}}catch(e){setResult({error:e.message})}}return <Panel title="PULSE Engineering"><p>Machine DNA, evidence and diagnostic orchestration.</p><button onClick={run}>Run diagnosis</button>{result&&<pre>{JSON.stringify(result,null,2)}</pre>}</Panel>}
function Shield(){const [hash,setHash]=useState(''),[result,setResult]=useState(null);async function scan(){try{setResult(await api('/shield/scan',{method:'POST',body:JSON.stringify({hash})}))}catch(e){setResult({error:e.message})}}return <Panel title="PULSE Shield"><p>Threat intelligence, malware scanning and security response.</p><input value={hash} onChange={e=>setHash(e.target.value)} placeholder="SHA-256 file hash"/><button disabled={!hash} onClick={scan}>Scan hash</button>{result&&<pre>{JSON.stringify(result,null,2)}</pre>}</Panel>}
function Chrysalis(){return <Panel title="PULSE CHRYSALIS"><p>Legacy assessment and controlled modernization paths.</p><div className="result">Assessment and upgrade execution are organization-scoped API operations.</div></Panel>}
function Edge(){return <Panel title="PULSE Edge"><p>SQLite durable queue with retrying cloud synchronization.</p><div className="result">Offline writes are queued locally and synchronized when connectivity returns.</div></Panel>}
function StandardApp(){const [domain,setDomain]=useState('automotive');const orgId=localStorage.getItem('pulse_org_id');return <main><header><div><span className="eyebrow">IVONIX / PULSE</span><h1>Machine Connect</h1><p>Every machine is a neuron.</p></div><OfflineIndicator/></header><div className="grid"><AiStudio/><AppForge/><CoreMonitor/><ReportBuilder/><DigitalTwin/><Aegis/><Intelligence/><LedgerExplorer/><FindSearch/><ServiceBuilder/><Ontology/><Engineering/><Shield/><Chrysalis/><Edge/><Batch5Panel organizationId={orgId}/><Panel title="Domain Explorer"><select value={domain} onChange={e=>setDomain(e.target.value)}>{DOMAINS.map(d=><option key={d}>{d}</option>)}</select><DomainDashboard domain={domain}/></Panel></div></main>}
function App(){if(window.location.pathname==='/key/activate')return <KeyActivate/>;const [founder,setFounder]=useState(undefined);useEffect(()=>{founderProfile().then(setFounder).catch(()=>setFounder(null));},[]);if(founder)return <FounderConsole/>;if(founder===undefined)return <div style={{padding:'2rem',fontFamily:'monospace'}}>Authenticating PULSE...</div>;return <StandardApp/>}
createRoot(document.getElementById('root')).render(<App/>);
