import React,{useEffect,useState} from 'react';

const API=import.meta.env.VITE_API_BASE_URL||'http://localhost:8081/api/v1';
const headers=()=>({Authorization:`Bearer ${localStorage.getItem('pulse_access_token')||''}`,'Content-Type':'application/json'});

export default function Aegis(){
 const [satellites,setSatellites]=useState([]),[selected,setSelected]=useState(null),[collisions,setCollisions]=useState([]),[comms,setComms]=useState([]),[name,setName]=useState(''),[norad,setNorad]=useState(''),[tle1,setTle1]=useState(''),[tle2,setTle2]=useState(''),[error,setError]=useState('');
 const load=async()=>{try{const r=await fetch(`${API}/aegis/satellites`,{headers:headers()});if(!r.ok)throw Error('Unable to load satellites');setSatellites(await r.json())}catch(e){setError(e.message)}};
 useEffect(()=>{load()},[]);
 const select=async s=>{setSelected(s);setError('');try{const [a,b]=await Promise.all([fetch(`${API}/aegis/satellites/${s.id}/collisions`,{headers:headers()}),fetch(`${API}/aegis/satellites/${s.id}/comms`,{headers:headers()})]);if(!a.ok||!b.ok)throw Error('Unable to load satellite status');setCollisions(await a.json());setComms(await b.json())}catch(e){setError(e.message)}};
 const register=async()=>{setError('');const r=await fetch(`${API}/aegis/satellites`,{method:'POST',headers:headers(),body:JSON.stringify({name,noradId:norad,tleLine1:tle1,tleLine2:tle2,status:'active'})});if(!r.ok){setError(await r.text());return}setName('');setNorad('');setTle1('');setTle2('');load()};
 return <main style={{padding:24,fontFamily:'system-ui',background:'#0B1D3A',color:'#E0E6ED',minHeight:'100vh'}}><h1>PULSE AEGIS</h1><p>Defensive Space Situational Awareness · AEG-020</p>{error&&<div style={{padding:10,border:'1px solid #EF476F',marginBottom:16}}>{error}</div>}<section style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:20}}><div style={{background:'#10284d',padding:16,borderRadius:12}}><h2>Satellite Catalog</h2>{satellites.map(s=><button key={s.id} onClick={()=>select(s)} style={{display:'block',width:'100%',margin:'8px 0',padding:12,textAlign:'left'}}>{s.name||'Unnamed'} · NORAD {s.noradId} · {s.status}</button>)}<h3>Register satellite</h3><input placeholder="Name" value={name} onChange={e=>setName(e.target.value)}/><input placeholder="NORAD ID" value={norad} onChange={e=>setNorad(e.target.value)}/><input placeholder="TLE line 1" value={tle1} onChange={e=>setTle1(e.target.value)}/><input placeholder="TLE line 2" value={tle2} onChange={e=>setTle2(e.target.value)}/><button onClick={register}>Register</button></div><div style={{background:'#10284d',padding:16,borderRadius:12}}><h2>{selected?.name||'Select a satellite'}</h2>{selected&&<><h3>Collision warnings</h3>{collisions.length?collisions.map(c=><div key={c.id}>{c.objectName||'Unknown object'} · {c.severity} · {c.missDistanceMeters??'—'} m</div>):<p>No recorded predictions.</p>}<h3>Communications</h3>{comms.length?comms.slice(0,10).map(c=><div key={c.id}>{c.timestamp} · uplink {c.uplinkStatus||'—'} · downlink {c.downlinkStatus||'—'} · interference {String(c.interferenceDetected)}</div>):<p>No recent communications records.</p>}</>}</div></section></main>
}
