package com.ivonix.pulse.ontology.domain;

import jakarta.validation.Valid; import jakarta.validation.constraints.*; import org.springframework.http.ResponseEntity; import org.springframework.security.core.context.SecurityContextHolder; import org.springframework.web.bind.annotation.*; import java.util.*;

final class DomainApi { static UUID user(){return (UUID)SecurityContextHolder.getContext().getAuthentication().getPrincipal();} static UUID org(){return (UUID)SecurityContextHolder.getContext().getAuthentication().getDetails();} }

record DomainIngestRequest(@NotNull UUID deviceId,@NotNull Map<String,Object> data){}

@RestController @RequestMapping("/api/v1/domains/automotive") class AutomotiveController { private final AutomotiveService s; AutomotiveController(AutomotiveService s){this.s=s;} @PostMapping("/ingest") ResponseEntity<Void> ingest(@Valid @RequestBody DomainIngestRequest r){s.ingest(r.deviceId(),DomainApi.org(),r.data());return ResponseEntity.noContent().build();} @GetMapping("/diagnose") DomainDiagnosticResult diagnose(@RequestParam UUID deviceId){return s.diagnose(deviceId,DomainApi.org());}}
@RestController @RequestMapping("/api/v1/domains/industrial") class IndustrialController { private final IndustrialService s; IndustrialController(IndustrialService s){this.s=s;} @PostMapping("/ingest") ResponseEntity<Void> ingest(@Valid @RequestBody DomainIngestRequest r){s.ingest(r.deviceId(),DomainApi.org(),r.data());return ResponseEntity.noContent().build();} @GetMapping("/diagnose") DomainDiagnosticResult diagnose(@RequestParam UUID deviceId){return s.diagnose(deviceId,DomainApi.org());}}
@RestController @RequestMapping("/api/v1/domains/robotics") class RoboticsController { private final RoboticsService s; RoboticsController(RoboticsService s){this.s=s;} @PostMapping("/ingest") ResponseEntity<Void> ingest(@Valid @RequestBody DomainIngestRequest r){s.ingest(r.deviceId(),DomainApi.org(),r.data());return ResponseEntity.noContent().build();} @GetMapping("/diagnose") DomainDiagnosticResult diagnose(@RequestParam UUID deviceId){return s.diagnose(deviceId,DomainApi.org());}}
@RestController @RequestMapping("/api/v1/domains/energy") class EnergyController { private final EnergyService s; EnergyController(EnergyService s){this.s=s;} @PostMapping("/ingest") ResponseEntity<Void> ingest(@Valid @RequestBody DomainIngestRequest r){s.ingest(r.deviceId(),DomainApi.org(),r.data());return ResponseEntity.noContent().build();} @GetMapping("/diagnose") DomainDiagnosticResult diagnose(@RequestParam UUID deviceId){return s.diagnose(deviceId,DomainApi.org());}}
@RestController @RequestMapping("/api/v1/domains/electronics") class ElectronicsController { private final ElectronicsService s; ElectronicsController(ElectronicsService s){this.s=s;} @PostMapping("/ingest") ResponseEntity<Void> ingest(@Valid @RequestBody DomainIngestRequest r){s.ingest(r.deviceId(),DomainApi.org(),r.data());return ResponseEntity.noContent().build();} @GetMapping("/diagnose") DomainDiagnosticResult diagnose(@RequestParam UUID deviceId){return s.diagnose(deviceId,DomainApi.org());}}
@RestController @RequestMapping("/api/v1/domains/agriculture") class AgricultureController { private final AgricultureService s; AgricultureController(AgricultureService s){this.s=s;} @PostMapping("/ingest") ResponseEntity<Void> ingest(@Valid @RequestBody DomainIngestRequest r){s.ingest(r.deviceId(),DomainApi.org(),r.data());return ResponseEntity.noContent().build();} @GetMapping("/diagnose") DomainDiagnosticResult diagnose(@RequestParam UUID deviceId){return s.diagnose(deviceId,DomainApi.org());}}
@RestController @RequestMapping("/api/v1/domains/aviation") class AviationController { private final AviationService s; AviationController(AviationService s){this.s=s;} @PostMapping("/ingest") ResponseEntity<Void> ingest(@Valid @RequestBody DomainIngestRequest r){s.ingest(r.deviceId(),DomainApi.org(),r.data());return ResponseEntity.noContent().build();} @GetMapping("/diagnose") DomainDiagnosticResult diagnose(@RequestParam UUID deviceId){return s.diagnose(deviceId,DomainApi.org());}}
@RestController @RequestMapping("/api/v1/domains/naval") class NavalController { private final NavalService s; NavalController(NavalService s){this.s=s;} @PostMapping("/ingest") ResponseEntity<Void> ingest(@Valid @RequestBody DomainIngestRequest r){s.ingest(r.deviceId(),DomainApi.org(),r.data());return ResponseEntity.noContent().build();} @GetMapping("/diagnose") DomainDiagnosticResult diagnose(@RequestParam UUID deviceId){return s.diagnose(deviceId,DomainApi.org());}}
@RestController @RequestMapping("/api/v1/domains/space") class SpaceController { private final SpaceService s; SpaceController(SpaceService s){this.s=s;} @PostMapping("/ingest") ResponseEntity<Void> ingest(@Valid @RequestBody DomainIngestRequest r){s.ingest(r.deviceId(),DomainApi.org(),r.data());return ResponseEntity.noContent().build();} @GetMapping("/diagnose") DomainDiagnosticResult diagnose(@RequestParam UUID deviceId){return s.diagnose(deviceId,DomainApi.org());}}