package com.ivonix.pulse.ontology.meet;
import com.fasterxml.jackson.databind.ObjectMapper; import com.ivonix.pulse.ontology.eventbus.EventBusService; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.client.RestTemplate; import org.springframework.http.*; import org.springframework.util.LinkedMultiValueMap; import org.springframework.util.MultiValueMap; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import java.nio.charset.StandardCharsets; import java.security.MessageDigest; import javax.crypto.Mac; import javax.crypto.spec.SecretKeySpec; import java.time.Instant; import java.util.*;
@Service public class MeetService{
 private final JdbcTemplate jdbc; private final ObjectMapper mapper; private final EventBusService bus; private final RestTemplate rest; private final String turnSecret; private final String turnUrls; private final String storageUrl; private final String storageKey;
 public MeetService(JdbcTemplate j,ObjectMapper m,EventBusService b,RestTemplate r,org.springframework.core.env.Environment e){jdbc=j;mapper=m;bus=b;rest=r;turnSecret=req(e.getProperty("TURN_SHARED_SECRET",System.getenv("TURN_SHARED_SECRET")),"TURN_SHARED_SECRET");turnUrls=req(e.getProperty("TURN_URLS",System.getenv("TURN_URLS")),"TURN_URLS");storageUrl=req(e.getProperty("SUPABASE_URL",System.getenv("SUPABASE_URL")),"SUPABASE_URL");storageKey=req(e.getProperty("SUPABASE_SERVICE_ROLE_KEY",System.getenv("SUPABASE_SERVICE_ROLE_KEY")),"SUPABASE_SERVICE_ROLE_KEY");}
 private String req(String v,String n){if(v==null||v.isBlank())throw new IllegalStateException(n+" is required");return v.replaceAll("/$","");}
 private void member(UUID org,UUID user){Integer n=jdbc.queryForObject("select count(*) from public.organization_members where organization_id=? and user_id=?",Integer.class,org,user);if(n==null||n<1)throw new SecurityException("Organization membership required");}
 private Map<String,Object> room(UUID id,UUID user){return jdbc.queryForObject("select r.* from public.meet_rooms r where r.id=? and public.pulse_is_org_member(r.organization_id)", (rs,n)->{Map<String,Object> x=new HashMap<>();x.put("id",rs.getObject("id"));x.put("organization_id",rs.getObject("organization_id"));x.put("name",rs.getString("name"));x.put("host_id",rs.getObject("host_id"));x.put("max_participants",rs.getInt("max_participants"));x.put("recording_enabled",rs.getBoolean("recording_enabled"));x.put("transcript_enabled",rs.getBoolean("transcript_enabled"));x.put("requires_approval",rs.getBoolean("requires_approval"));x.put("status",rs.getString("status"));return x;},id);}
 public UUID create(UUID org,String name,UUID host,Map<String,Object> opts){member(org,host);int max=((Number)opts.getOrDefault("maxParticipants",20)).intValue();if(max<2||max>100)throw new IllegalArgumentException("Invalid participant limit");UUID id=UUID.randomUUID();jdbc.update("insert into public.meet_rooms(id,organization_id,name,host_id,max_participants,recording_enabled,transcript_enabled,requires_approval) values(?,?,?,?,?,?,?,?)",id,org,name,host,max,Boolean.TRUE.equals(opts.get("recordingEnabled")),Boolean.TRUE.equals(opts.get("transcriptEnabled")),Boolean.TRUE.equals(opts.get("requiresApproval")));jdbc.update("insert into public.meet_participants(room_id,user_id,role,status,joined_at) values(?,?, 'host','joined',now())",id,host);bus.publish("meet.room_created","pulse-meet",Map.of("roomId",id,"hostId",host),org,id.toString());return id;}
 @Transactional public Map<String,Object> join(UUID roomId,UUID user){Map<String,Object> r=room(roomId,user);UUID org=(UUID)r.get("organization_id");member(org,user);if(Set.of("ended").contains(r.get("status")))throw new IllegalStateException("Room ended");if(Boolean.TRUE.equals(r.get("requires_approval"))){Integer approved=jdbc.queryForObject("select count(*) from public.meet_participants where room_id=? and user_id=? and status='joined'",Integer.class,roomId,user);if(approved==null||approved==0){jdbc.update("insert into public.meet_participants(room_id,user_id,status) values(?,?, 'invited') on conflict(room_id,user_id) do nothing",roomId,user);throw new PendingApprovalException();}}
 jdbc.queryForObject("select pg_advisory_xact_lock(hashtext(?))",Object.class,"meet:"+roomId);Integer count=jdbc.queryForObject("select count(*) from public.meet_participants where room_id=? and status='joined'",Integer.class,roomId);if(count!=null&&count>=((Number)r.get("max_participants")).intValue()&&jdbc.queryForObject("select count(*) from public.meet_participants where room_id=? and user_id=? and status='joined'",Integer.class,roomId,user)==0)throw new IllegalStateException("Room is full");jdbc.update("insert into public.meet_participants(room_id,user_id,status,joined_at) values(?,?, 'joined',now()) on conflict(room_id,user_id) do update set status='joined',joined_at=now(),left_at=null",roomId,user);jdbc.update("update public.meet_rooms set status='live',started_at=coalesce(started_at,now()) where id=? and status='scheduled'",roomId);List<Map<String,Object>> roster=jdbc.queryForList("select user_id,display_name,role,status from public.meet_participants where room_id=? and status in('joined','invited') order by joined_at",roomId);return Map.of("room",r,"roster",roster,"iceServers",List.of(Map.of("urls",turnUrls),Map.of("urls",turnUrls,"username",turnUsername(user),"credential",turnCredential(user),"ttl",3600)));}
 public void leave(UUID room,UUID user){Map<String,Object> r=room(room,user);jdbc.update("update public.meet_participants set status='left',left_at=now() where room_id=? and user_id=?",room,user);jdbc.update("update public.meet_rooms set ended_at=case when not exists(select 1 from public.meet_participants where room_id=? and status='joined' and role='host') then coalesce(ended_at,now()) else ended_at end where id=?",room,room);}
 public void signal(UUID room,UUID sender,UUID recipient,String type,Map<String,Object> payload){if(!Set.of("offer","answer","ice","join","leave").contains(type))throw new IllegalArgumentException("Invalid signal type");Map<String,Object> r=room(room,sender);UUID org=(UUID)r.get("organization_id");member(org,sender);Integer s=jdbc.queryForObject("select count(*) from public.meet_participants where room_id=? and user_id=? and status='joined'",Integer.class,room,sender);Integer t=jdbc.queryForObject("select count(*) from public.meet_participants where room_id=? and user_id=? and status in('joined','invited')",Integer.class,room,recipient);if(s==null||s!=1||t==null||t!=1)throw new SecurityException("Both signaling endpoints must be room participants");if(payload==null||payload.size()>20)throw new IllegalArgumentException("Invalid signal payload");try{jdbc.update("insert into public.meet_signals(room_id,sender_id,recipient_id,signal_type,payload) values(?,?,?,?,?::jsonb)",room,sender,recipient,type,mapper.writeValueAsString(payload));}catch(Exception e){throw new IllegalArgumentException("Invalid signal payload",e);}}
 public Map<String,String> turn(UUID user){return Map.of("username",turnUsername(user),"credential",turnCredential(user),"ttl","3600","urls",turnUrls);}
 private String turnUsername(UUID user){return (Instant.now().getEpochSecond()+3600)+":"+user;}
 private String turnCredential(UUID user){String username=turnUsername(user);try{Mac m=Mac.getInstance("HmacSHA1");m.init(new SecretKeySpec(turnSecret.getBytes(StandardCharsets.UTF_8),"HmacSHA1"));return Base64.getEncoder().encodeToString(m.doFinal(username.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException("TURN credential generation failed",e);}}
 public UUID startRecording(UUID room,UUID host){Map<String,Object> r=room(room,host);if(!host.equals(r.get("host_id")))throw new SecurityException("Host required");if(!Boolean.TRUE.equals(r.get("recording_enabled")))throw new IllegalStateException("Recording disabled");UUID id=UUID.randomUUID();jdbc.update("insert into public.meet_recordings(id,room_id) values(?,?)",id,room);return id;}
 public void uploadRecording(UUID recording,UUID user,MultipartFile file){if(file==null||file.isEmpty()||file.getSize()>2L*1024*1024*1024)throw new IllegalArgumentException("Invalid recording");Map<String,Object> r=jdbc.queryForMap("select r.room_id,m.organization_id,m.host_id from public.meet_recordings r join public.meet_rooms m on m.id=r.room_id where r.id=?",recording);member((UUID)r.get("organization_id"),user);if(!user.equals(r.get("host_id")))throw new SecurityException("Host required");String path="meet/"+r.get("organization_id")+"/"+recording+".webm";HttpHeaders h=new HttpHeaders();h.set("Authorization","Bearer "+storageKey);h.set("apikey",storageKey);h.setContentType(MediaType.parseMediaType(file.getContentType()==null?"video/webm":file.getContentType()));ResponseEntity<String> resp=rest.exchange(storageUrl+"/storage/v1/object/recordings/"+path,HttpMethod.POST,new HttpEntity<>(file.getBytes(),h),String.class);if(!resp.getStatusCode().is2xxSuccessful())throw new IllegalStateException("Recording storage upload failed");jdbc.update("update public.meet_recordings set storage_path=?,size_bytes=?,status='processing',ended_at=coalesce(ended_at,now()),duration_seconds=coalesce(duration_seconds,extract(epoch from(now()-started_at))::int) where id=?",path,file.getSize(),recording);UUID room=(UUID)r.get("room_id");bus.publish("meet.recording_ready","pulse-meet",Map.of("recordingId",recording,"roomId",room,"storagePath",path),null,recording.toString());}
 public static class PendingApprovalException extends RuntimeException{}
}