import os
import time
from pathlib import Path
from typing import Any

import numpy as np
import onnxruntime as ort
import requests
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel

app = FastAPI(title="PULSE CORE Runtime", version="0.1.0")
SUPABASE_URL = os.environ.get("SUPABASE_URL", "").rstrip("/")
SUPABASE_SERVICE_ROLE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "")
MODEL_ROOT = Path(os.environ.get("CORE_MODEL_ROOT", "/models")).resolve()

class InferenceRequest(BaseModel):
    job_id: str
    model_id: str
    input_data: dict[str, Any]


def supabase_request(method: str, path: str, **kwargs):
    if not SUPABASE_URL or not SUPABASE_SERVICE_ROLE_KEY:
        raise RuntimeError("Supabase runtime credentials are not configured")
    headers = kwargs.pop("headers", {})
    headers.update({"apikey": SUPABASE_SERVICE_ROLE_KEY, "Authorization": f"Bearer {SUPABASE_SERVICE_ROLE_KEY}"})
    response = requests.request(method, f"{SUPABASE_URL}/rest/v1/{path}", headers=headers, timeout=20, **kwargs)
    response.raise_for_status()
    return response


def fetch_model(model_id: str):
    response = supabase_request("GET", "core_models", params={"id": f"eq.{model_id}", "select": "id,organization_id,model_path,input_shape,output_shape,framework"})
    rows = response.json()
    if len(rows) != 1:
        raise RuntimeError("Model not found")
    return rows[0]


def update_job(job_id: str, status: str, output=None, latency_ms=None, started=False, completed=False):
    payload = {"status": status}
    if started:
        payload["started_at"] = "now()"
    if completed:
        payload["completed_at"] = "now()"
    if output is not None:
        payload["output_data"] = output
    if latency_ms is not None:
        payload["latency_ms"] = latency_ms
    # PostgREST does not evaluate now() in JSON payloads, so timestamps are generated by SQL defaults/worker time below.
    import datetime
    if started:
        payload["started_at"] = datetime.datetime.now(datetime.timezone.utc).isoformat()
    if completed:
        payload["completed_at"] = datetime.datetime.now(datetime.timezone.utc).isoformat()
    supabase_request("PATCH", "inference_jobs", params={"id": f"eq.{job_id}"}, json=payload)


def resolve_model_path(model_path: str) -> Path:
    path = Path(model_path)
    if not path.is_absolute():
        path = MODEL_ROOT / path
    path = path.resolve()
    if MODEL_ROOT not in path.parents and path != MODEL_ROOT:
        raise RuntimeError("Model path escapes CORE_MODEL_ROOT")
    if not path.is_file():
        raise RuntimeError("Model file is unavailable to the CORE runtime")
    return path


def run_inference(req: InferenceRequest):
    update_job(req.job_id, "running", started=True)
    started = time.perf_counter()
    try:
        model = fetch_model(req.model_id)
        if model["framework"] != "onnx":
            raise RuntimeError("This runtime currently supports ONNX models")
        model_path = resolve_model_path(model["model_path"])

        options = ort.SessionOptions()
        options.graph_optimization_level = ort.GraphOptimizationLevel.ORT_ENABLE_ALL
        options.intra_op_num_threads = max(1, os.cpu_count() or 1)
        providers = ort.get_available_providers()
        provider_order = [p for p in ("CUDAExecutionProvider", "CPUExecutionProvider") if p in providers]
        if not provider_order:
            provider_order = ["CPUExecutionProvider"]
        session = ort.InferenceSession(str(model_path), options, providers=provider_order)
        input_name = session.get_inputs()[0].name
        data = req.input_data.get("data")
        if data is None:
            raise RuntimeError("input_data.data is required")
        array = np.asarray(data, dtype=np.float32)
        if model.get("input_shape"):
            array = array.reshape(tuple(model["input_shape"]))

        outputs = session.run(None, {input_name: array})
        latency_ms = (time.perf_counter() - started) * 1000.0
        output = {"output": outputs[0].tolist()}
        update_job(req.job_id, "completed", output=output, latency_ms=latency_ms, completed=True)
        return latency_ms
    except Exception as exc:
        update_job(req.job_id, "failed", output={"error": str(exc)}, latency_ms=(time.perf_counter() - started) * 1000.0, completed=True)
        raise


@app.get("/health")
def health():
    return {"status": "ok", "providers": ort.get_available_providers()}


@app.post("/infer")
def infer(req: InferenceRequest):
    # The API returns only after the job has been accepted for execution by this process.
    # A production queue/worker pool can be added without changing the job contract.
    try:
        run_inference(req)
    except Exception as exc:
        raise HTTPException(status_code=500, detail=str(exc)) from exc
    return {"status": "completed", "job_id": req.job_id}
