package com.ivonix.pulse.ontology.edge;

import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Component; import jakarta.annotation.PostConstruct; import jakarta.annotation.PreDestroy; import java.sql.*; import java.util.*;
@Component public class OfflineDatabase implements AutoCloseable {
 private final String url; private Connection connection;
 public OfflineDatabase(@Value("${PULSE_EDGE_DB_URL:jdbc:sqlite:pulse-local.db}") String url){this.url=url;}
 @PostConstruct public synchronized void init() throws SQLException {connection=DriverManager.getConnection(url);try(Statement s=connection.createStatement()){s.executeUpdate("PRAGMA journal_mode=WAL");s.executeUpdate("CREATE TABLE IF NOT EXISTS sync_queue(id INTEGER PRIMARY KEY AUTOINCREMENT,organization_id TEXT NOT NULL,table_name TEXT NOT NULL,record_id TEXT NOT NULL,operation TEXT NOT NULL,data TEXT NOT NULL,attempts INTEGER NOT NULL DEFAULT 0,last_error TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,synced INTEGER NOT NULL DEFAULT 0)");s.executeUpdate("CREATE INDEX IF NOT EXISTS idx_sync_pending ON sync_queue(synced,created_at)");}}
 public synchronized void enqueue(UUID org,UUID recordId,String table,String operation,String json) throws SQLException {if(!Set.of("device_telemetry","find_searches","find_matches","ontology_entities","ontology_relationships").contains(table))throw new IllegalArgumentException("Table is not syncable");if(!Set.of("insert","update").contains(operation))throw new IllegalArgumentException("Operation is not syncable");try(PreparedStatement p=connection.prepareStatement("insert into sync_queue(organization_id,table_name,record_id,operation,data) values(?,?,?,?,?)")){p.setString(1,org.toString());p.setString(2,table);p.setString(3,recordId.toString());p.setString(4,operation);p.setString(5,json);p.executeUpdate();}}
 public synchronized List<Map<String,Object>> pending(int limit) throws SQLException {List<Map<String,Object>> out=new ArrayList<>();try(PreparedStatement p=connection.prepareStatement("select * from sync_queue where synced=0 order by id limit ?")){p.setInt(1,Math.max(1,Math.min(limit,100)));try(ResultSet r=p.executeQuery()){while(r.next()){Map<String,Object> m=new HashMap<>();m.put("id",r.getLong("id"));m.put("organization_id",r.getString("organization_id"));m.put("table_name",r.getString("table_name"));m.put("record_id",r.getString("record_id"));m.put("operation",r.getString("operation"));m.put("data",r.getString("data"));out.add(m);}}}return out;}
 public synchronized void markSynced(long id) throws SQLException {try(PreparedStatement p=connection.prepareStatement("update sync_queue set synced=1 where id=?")){p.setLong(1,id);p.executeUpdate();}}
 public synchronized void markFailed(long id,String error) throws SQLException {try(PreparedStatement p=connection.prepareStatement("update sync_queue set attempts=attempts+1,last_error=? where id=?")){p.setString(1,error==null?"sync failed":error.substring(0,Math.min(1000,error.length())));p.setLong(2,id);p.executeUpdate();}}
 @PreDestroy public synchronized void close() throws SQLException {if(connection!=null)connection.close();}
}