package com.ivonix.pulse.ontology.key;
import org.springframework.beans.factory.annotation.Value; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.stereotype.Service; import org.springframework.web.client.RestTemplate;
import javax.crypto.Cipher; import javax.crypto.spec.GCMParameterSpec; import javax.crypto.spec.SecretKeySpec; import java.security.KeyPair; import java.security.KeyPairGenerator; import java.security.SecureRandom; import java.util.*;
@Service public class KeyService {
 private final JdbcTemplate jdbc; private final RestTemplate rest; private final String cryptoUrl; private final byte[] masterKey; private final SecureRandom random=new SecureRandom();
 public KeyService(JdbcTemplate jdbc,RestTemplate rest,@Value("${PULSE_CRYPTO_URL:http://127.0.0.1:8092}") String cryptoUrl){this.jdbc=jdbc;this.rest=rest;this.cryptoUrl=cryptoUrl.replaceAll("/$","");String raw=System.getenv("PULSE_MASTER_KEY");if(raw==null||raw.isBlank())throw new IllegalStateException("PULSE_MASTER_KEY is required");try{masterKey=Base64.getDecoder().decode(raw);}catch(Exception e){throw new IllegalStateException("PULSE_MASTER_KEY must be base64",e);}if(masterKey.length!=32)throw new IllegalStateException("PULSE_MASTER_KEY must decode to 32 bytes");}
 public KeyView create(UUID userId,UUID orgId,KeyRequest r){requireMember(orgId,userId);String type=req(r.keyType(),"keyType"),purpose=req(r.purpose(),"purpose"),alias=req(r.keyAlias(),"keyAlias");if(!Set.of("aes-256","rsa-2048","ec-p256").contains(type))throw new IllegalArgumentException("Unsupported key type");if(!Set.of("encryption","signing","key_exchange").contains(purpose))throw new IllegalArgumentException("Unsupported purpose");KeyMaterial m=generate(type);UUID id=UUID.randomUUID();jdbc.update("insert into public.crypto_keys(id,organization_id,key_alias,key_type,purpose,hsm_backed,public_key,encrypted_private_key,created_by) values (?,?,?,?,?,?,?,?,?)",id,orgId,alias,type,purpose,false,m.publicKey(),seal(m.privateKey()),userId);audit(id,"rotate",userId,"success");return get(id,userId,orgId);}
 public String encrypt(UUID userId,UUID orgId,UUID keyId,String plaintext){authorizeKey(keyId,userId,orgId,"encryption");return encryptInternal(orgId,keyId,plaintext,userId);}
 public String decrypt(UUID userId,UUID orgId,UUID keyId,String ciphertext){authorizeKey(keyId,userId,orgId,"encryption");return decryptInternal(orgId,keyId,ciphertext,userId);}
 public String encryptSystem(UUID orgId,UUID keyId,String plaintext){authorizeSystemKey(keyId,orgId,"encryption");return encryptInternal(orgId,keyId,plaintext,null);}
 public String decryptSystem(UUID orgId,UUID keyId,String ciphertext){authorizeSystemKey(keyId,orgId,"encryption");return decryptInternal(orgId,keyId,ciphertext,null);}
 private String encryptInternal(UUID orgId,UUID keyId,String plaintext,UUID actor){CryptoResponse r=rest.postForObject(cryptoUrl+"/v1/encrypt",new CryptoRequest(keyId,plaintext),CryptoResponse.class);if(r==null||r.ciphertext()==null)throw new IllegalStateException("Crypto service returned no ciphertext");audit(keyId,"encrypt",actor,"success");return r.ciphertext();}
 private String decryptInternal(UUID orgId,UUID keyId,String ciphertext,UUID actor){CryptoResponse r=rest.postForObject(cryptoUrl+"/v1/decrypt",new CryptoRequest(keyId,ciphertext),CryptoResponse.class);if(r==null||r.plaintext()==null)throw new IllegalStateException("Crypto service returned no plaintext");audit(keyId,"decrypt",actor,"success");return r.plaintext();}
 public KeyView get(UUID id,UUID userId,UUID orgId){authorizeKey(id,userId,orgId,null);return jdbc.queryForObject("select id,key_alias,key_type,purpose,hsm_backed,public_key,created_at,last_rotated_at,rotation_interval_days,status from public.crypto_keys where id=? and organization_id=?",(rs,n)->view(rs),id,orgId);}
 public List<KeyView> list(UUID userId,UUID orgId){requireMember(orgId,userId);return jdbc.query("select id,key_alias,key_type,purpose,hsm_backed,public_key,created_at,last_rotated_at,rotation_interval_days,status from public.crypto_keys where organization_id=? order by created_at desc",(rs,n)->view(rs),orgId);}
 private void authorizeSystemKey(UUID id,UUID orgId,String purpose){KeyView k=getUnchecked(id,orgId);if(k==null||!"active".equals(k.status()))throw new SecurityException("Key unavailable");if(purpose!=null&&!purpose.equals(k.purpose()))throw new SecurityException("Key purpose mismatch");}
 private KeyView authorizeKey(UUID id,UUID userId,UUID orgId,String purpose){requireMember(orgId,userId);KeyView k=getUnchecked(id,orgId);if(k==null||!"active".equals(k.status()))throw new SecurityException("Key unavailable");if(purpose!=null&&!purpose.equals(k.purpose()))throw new SecurityException("Key purpose mismatch");return k;}
 private KeyView getUnchecked(UUID id,UUID orgId){try{return jdbc.queryForObject("select id,key_alias,key_type,purpose,hsm_backed,public_key,created_at,last_rotated_at,rotation_interval_days,status from public.crypto_keys where id=? and organization_id=?",(rs,n)->view(rs),id,orgId);}catch(Exception e){return null;}}
 private KeyView view(java.sql.ResultSet rs)throws java.sql.SQLException{return new KeyView((UUID)rs.getObject("id"),rs.getString("key_alias"),rs.getString("key_type"),rs.getString("purpose"),rs.getBoolean("hsm_backed"),rs.getString("public_key"),rs.getObject("created_at",java.time.Instant.class),rs.getObject("last_rotated_at",java.time.Instant.class),rs.getInt("rotation_interval_days"),rs.getString("status"));}
 private void requireMember(UUID org,UUID user){Integer n=jdbc.queryForObject("select count(*) from public.organization_members where organization_id=? and user_id=?",Integer.class,org,user);if(n==null||n<1)throw new SecurityException("Organization membership required");}
 private void audit(UUID id,String op,UUID user,String status){jdbc.update("insert into public.crypto_operations(key_id,operation_type,requested_by,status) values (?,?,?,?)",id,op,user,status);}
 private String req(String s,String n){if(s==null||s.isBlank())throw new IllegalArgumentException(n+" required");return s.trim();}
 private KeyMaterial generate(String type){try{if("aes-256".equals(type)){byte[] b=new byte[32];random.nextBytes(b);return new KeyMaterial(null,b);}KeyPairGenerator g=KeyPairGenerator.getInstance("RSA");g.initialize(2048);KeyPair p=g.generateKeyPair();return new KeyMaterial(Base64.getEncoder().encodeToString(p.getPublic().getEncoded()),p.getPrivate().getEncoded());}catch(Exception e){throw new IllegalStateException("Key generation failed",e);}}
 private String seal(byte[] plain){try{byte[] iv=new byte[12];random.nextBytes(iv);Cipher c=Cipher.getInstance("AES/GCM/NoPadding");c.init(Cipher.ENCRYPT_MODE,new SecretKeySpec(masterKey,"AES"),new GCMParameterSpec(128,iv));byte[] out=c.doFinal(plain);byte[] all=new byte[iv.length+out.length];System.arraycopy(iv,0,all,0,iv.length);System.arraycopy(out,0,all,iv.length,out.length);return Base64.getEncoder().encodeToString(all);}catch(Exception e){throw new IllegalStateException("Private material encryption failed",e);}}
 public record KeyRequest(String organizationId,String keyAlias,String keyType,String purpose){} public record KeyView(UUID id,String keyAlias,String keyType,String purpose,boolean hsmBacked,String publicKey,java.time.Instant createdAt,java.time.Instant lastRotatedAt,int rotationIntervalDays,String status){} public record CryptoRequest(UUID keyId,String data){} public record CryptoResponse(String ciphertext,String plaintext){} private record KeyMaterial(String publicKey,byte[] privateKey){}
}