package com.ivonix.pulse.ontology.academy;
import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.security.core.Authentication; import org.springframework.web.bind.annotation.*; import java.util.*;
@RestController @RequestMapping("/api/academy") public class AcademyController{private final AcademyService service;private final JdbcTemplate jdbc;private final CertificateSigner signer;public AcademyController(AcademyService s,JdbcTemplate j,CertificateSigner cs){service=s;jdbc=j;signer=cs;}private UUID u(Authentication a){return UUID.fromString(a.getName());}
@GetMapping("/courses") public Object courses(@RequestParam UUID organizationId,Authentication a){return service.courses(organizationId,u(a));}
@PostMapping("/courses/{courseId}/enroll") public Object enroll(@PathVariable UUID courseId,@RequestParam UUID organizationId,Authentication a){return Map.of("enrollmentId",service.enroll(organizationId,courseId,u(a)));}
@PostMapping("/lessons/{lessonId}/complete") public Object complete(@PathVariable UUID lessonId,@RequestBody CompleteRequest r,Authentication a){service.completeLesson(r.organizationId(),r.enrollmentId(),lessonId,u(a),r.timeSpentSeconds());return Map.of("ok",true);}
@PostMapping("/quizzes/{quizId}/submit") public Object submit(@PathVariable UUID quizId,@RequestBody QuizRequest r,Authentication a){return service.submitQuiz(r.organizationId(),quizId,u(a),r.answers());}
@PostMapping("/courses/{courseId}/certificate") public Object certificate(@PathVariable UUID courseId,@RequestParam UUID organizationId,Authentication a){return Map.of("certificateId",service.issueCertificate(organizationId,courseId,u(a)));}
@GetMapping("/certificates/verify/{number}") public Object verify(@PathVariable String number){try{return jdbc.queryForObject("select certificate_number,course_id,issued_at,expires_at,revoked,signature,public_key,verification_payload from public.academy_certificates where certificate_number=?",(rs,n)->{String payload=rs.getString("verification_payload");boolean valid=signer.verify(payload,rs.getString("signature"))&&signer.publicKey().equals(rs.getString("public_key"))&&!rs.getBoolean("revoked")&&(rs.getTimestamp("expires_at")==null||rs.getTimestamp("expires_at").toInstant().isAfter(java.time.Instant.now()));return Map.of("certificateNumber",rs.getString("certificate_number"),"courseId",rs.getObject("course_id"),"issuedAt",rs.getTimestamp("issued_at").toInstant(),"valid",valid);},number);}catch(Exception e){throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.NOT_FOUND,"Certificate not found");}}
public record CompleteRequest(UUID organizationId,UUID enrollmentId,int timeSpentSeconds){}public record QuizRequest(UUID organizationId,List<Object> answers){}
}