package com.ivonix.pulse.ontology.academy;
import org.springframework.beans.factory.annotation.Value; import org.springframework.stereotype.Service; import java.security.*; import java.security.spec.PKCS8EncodedKeySpec; import java.security.spec.X509EncodedKeySpec; import java.util.*;
@Service public class CertificateSigner {
 private final PrivateKey privateKey; private final String publicKey;
 public CertificateSigner(@Value("${PULSE_CERT_SIGNING_PRIVATE_KEY:}") String encoded,@Value("${PULSE_CERT_SIGNING_PUBLIC_KEY:}") String configured){try{if(encoded==null||encoded.isBlank())throw new IllegalStateException("PULSE_CERT_SIGNING_PRIVATE_KEY is required");byte[] raw=Base64.getDecoder().decode(encoded);KeyFactory f=KeyFactory.getInstance("Ed25519");privateKey=f.generatePrivate(new PKCS8EncodedKeySpec(raw));PublicKey pub=privateKeyToPublic(privateKey);publicKey=configured==null||configured.isBlank()?Base64.getEncoder().encodeToString(pub.getEncoded()):configured.trim();}catch(Exception e){throw new IllegalStateException("Ed25519 certificate signer unavailable",e);}}
 private PublicKey privateKeyToPublic(PrivateKey k)throws Exception{String p=System.getenv("PULSE_CERT_SIGNING_PUBLIC_KEY");if(p==null||p.isBlank())throw new IllegalStateException("PULSE_CERT_SIGNING_PUBLIC_KEY is required");return KeyFactory.getInstance("Ed25519").generatePublic(new X509EncodedKeySpec(Base64.getDecoder().decode(p)));}
 public String sign(String payload){try{Signature s=Signature.getInstance("Ed25519");s.initSign(privateKey);s.update(payload.getBytes(java.nio.charset.StandardCharsets.UTF_8));return Base64.getUrlEncoder().withoutPadding().encodeToString(s.sign());}catch(Exception e){throw new IllegalStateException("Certificate signing failed",e);}}
 public String publicKey(){return publicKey;}
 public boolean verify(String payload,String signature){try{Signature s=Signature.getInstance("Ed25519");KeyFactory f=KeyFactory.getInstance("Ed25519");PublicKey p=f.generatePublic(new X509EncodedKeySpec(Base64.getDecoder().decode(publicKey)));s.initVerify(p);s.update(payload.getBytes(java.nio.charset.StandardCharsets.UTF_8));return s.verify(Base64.getUrlDecoder().decode(signature));}catch(Exception e){return false;}}
}