-- PULSE platform services 56-59. Idempotent DDL; no destructive changes.

CREATE TABLE IF NOT EXISTS public.privacy_consents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE,purpose text NOT NULL CHECK(purpose IN('marketing','analytics','ai_training')),granted boolean NOT NULL,granted_at timestamptz NOT NULL DEFAULT now(),revoked_at timestamptz,version text,ip_address inet,user_agent text);
CREATE INDEX IF NOT EXISTS idx_consent_user_purpose ON public.privacy_consents(user_id,purpose,granted_at DESC);
CREATE TABLE IF NOT EXISTS public.privacy_dsar_requests (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid REFERENCES auth.users(id),request_type text NOT NULL CHECK(request_type IN('access','portability','erasure','rectification','restriction')),status text NOT NULL DEFAULT 'received' CHECK(status IN('received','verifying','in_progress','completed','rejected')),submitted_at timestamptz NOT NULL DEFAULT now(),verified_at timestamptz,completed_at timestamptz,rejection_reason text,result_path text,sla_due_at timestamptz NOT NULL DEFAULT now()+interval '30 days');
ALTER TABLE public.privacy_dsar_requests ADD COLUMN IF NOT EXISTS result_payload jsonb;
CREATE INDEX IF NOT EXISTS idx_dsar_open ON public.privacy_dsar_requests(status,sla_due_at) WHERE status NOT IN('completed','rejected');
CREATE TABLE IF NOT EXISTS public.privacy_data_lineage (id bigserial PRIMARY KEY,data_category text NOT NULL,source_table text NOT NULL,source_column text,processor_service text NOT NULL,downstream jsonb NOT NULL DEFAULT '[]'::jsonb,retention_days int,legal_basis text,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.privacy_erasure_jobs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),dsar_request_id uuid REFERENCES public.privacy_dsar_requests(id) ON DELETE CASCADE,user_id uuid NOT NULL,status text NOT NULL DEFAULT 'running',tables_processed jsonb NOT NULL DEFAULT '[]'::jsonb,tables_skipped jsonb NOT NULL DEFAULT '[]'::jsonb,rows_deleted bigint NOT NULL DEFAULT 0,completed_at timestamptz,error_message text);

CREATE TABLE IF NOT EXISTS public.trust_signals (id bigserial PRIMARY KEY,user_id uuid REFERENCES auth.users(id),device_id uuid REFERENCES public.devices(id),signal_type text NOT NULL,score numeric NOT NULL CHECK(score>=0 AND score<=1),details jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_trust_signals_user ON public.trust_signals(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS public.trust_risk_profiles (user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,risk_level text NOT NULL DEFAULT 'low',risk_score numeric NOT NULL DEFAULT 0,factors jsonb NOT NULL DEFAULT '{}'::jsonb,requires_mfa boolean NOT NULL DEFAULT false,last_reviewed_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE IF NOT EXISTS public.trust_rules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,signal_type text NOT NULL,condition jsonb NOT NULL,action jsonb NOT NULL,enabled boolean NOT NULL DEFAULT true,priority int NOT NULL DEFAULT 100);
CREATE TABLE IF NOT EXISTS public.trust_blocks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),subject_type text NOT NULL,subject_value text NOT NULL,reason text,blocked_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz,blocked_by uuid REFERENCES auth.users(id),UNIQUE(subject_type,subject_value));
CREATE TABLE IF NOT EXISTS public.trust_content_reports (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reporter_id uuid REFERENCES auth.users(id),target_type text NOT NULL,target_id text NOT NULL,reason text NOT NULL,status text NOT NULL DEFAULT 'open',reviewed_by uuid REFERENCES auth.users(id),reviewed_at timestamptz,resolution text,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_trust_reports_open ON public.trust_content_reports(status,created_at DESC);

CREATE TABLE IF NOT EXISTS public.finops_cost_events (id bigserial PRIMARY KEY,organization_id uuid REFERENCES public.organizations(id),service text NOT NULL,resource_type text,quantity numeric NOT NULL CHECK(quantity>=0),unit text NOT NULL,unit_cost_usd numeric NOT NULL CHECK(unit_cost_usd>=0),total_cost_usd numeric NOT NULL CHECK(total_cost_usd>=0),tags jsonb NOT NULL DEFAULT '{}'::jsonb,event_time timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_finops_org_time ON public.finops_cost_events(organization_id,event_time DESC);
CREATE INDEX IF NOT EXISTS idx_finops_service_time ON public.finops_cost_events(service,event_time DESC);
CREATE TABLE IF NOT EXISTS public.finops_rate_card (service text NOT NULL,resource_type text NOT NULL,unit text NOT NULL,unit_cost_usd numeric NOT NULL CHECK(unit_cost_usd>=0),region text,effective_from date NOT NULL,effective_to date,PRIMARY KEY(service,resource_type,unit,region,effective_from));
CREATE TABLE IF NOT EXISTS public.finops_tenant_profitability (id bigserial PRIMARY KEY,organization_id uuid REFERENCES public.organizations(id),period_start date NOT NULL,period_end date NOT NULL,revenue_usd numeric NOT NULL,cogs_usd numeric NOT NULL,gross_margin_usd numeric GENERATED ALWAYS AS(revenue_usd-cogs_usd) STORED,gross_margin_pct numeric GENERATED ALWAYS AS(CASE WHEN revenue_usd=0 THEN NULL ELSE(revenue_usd-cogs_usd)/revenue_usd*100 END) STORED,UNIQUE(organization_id,period_start,period_end));
CREATE TABLE IF NOT EXISTS public.finops_anomalies (id bigserial PRIMARY KEY,organization_id uuid REFERENCES public.organizations(id),service text,expected_usd numeric,observed_usd numeric,deviation_pct numeric,detected_at timestamptz NOT NULL DEFAULT now(),resolved_at timestamptz);
INSERT INTO public.finops_rate_card(service,resource_type,unit,unit_cost_usd,region,effective_from,effective_to) VALUES('compute','k8s','vCPU_hour',0.04,'us-east-1','2024-01-01',NULL),('compute','k8s','GB_hour',0.005,'us-east-1','2024-01-01',NULL),('storage','postgres','GB_month',0.115,'us-east-1','2024-01-01',NULL),('storage','s3','GB_month',0.023,'us-east-1','2024-01-01',NULL),('egress','s3','GB',0.09,'us-east-1','2024-01-01',NULL),('ai_inference','gpu','gpu_second',0.0004,'us-east-1','2024-01-01',NULL),('ai_inference','cpu','cpu_second',0.000017,'us-east-1','2024-01-01',NULL) ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS public.runbook_teams (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid REFERENCES public.organizations(id) ON DELETE CASCADE,name text NOT NULL,slack_channel text,email text);
CREATE TABLE IF NOT EXISTS public.runbook_schedules (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),team_id uuid REFERENCES public.runbook_teams(id) ON DELETE CASCADE,user_id uuid REFERENCES auth.users(id),starts_at timestamptz NOT NULL,ends_at timestamptz NOT NULL,role text NOT NULL DEFAULT 'primary' CHECK(role IN('primary','secondary')),CHECK(ends_at>starts_at));
CREATE INDEX IF NOT EXISTS idx_schedules_window ON public.runbook_schedules(starts_at,ends_at);
CREATE TABLE IF NOT EXISTS public.runbook_incidents (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),organization_id uuid REFERENCES public.organizations(id),title text NOT NULL,severity text NOT NULL CHECK(severity IN('SEV1','SEV2','SEV3','SEV4')),status text NOT NULL DEFAULT 'open' CHECK(status IN('open','mitigated','resolved')),commander uuid REFERENCES auth.users(id),declared_by uuid REFERENCES auth.users(id),declared_at timestamptz NOT NULL DEFAULT now(),mitigated_at timestamptz,resolved_at timestamptz,affected_services text[],customer_impact text,root_cause text,postmortem_path text);
CREATE INDEX IF NOT EXISTS idx_incidents_open ON public.runbook_incidents(status,declared_at DESC) WHERE status<>'resolved';
CREATE TABLE IF NOT EXISTS public.runbook_timeline (id bigserial PRIMARY KEY,incident_id uuid REFERENCES public.runbook_incidents(id) ON DELETE CASCADE,event_time timestamptz NOT NULL DEFAULT now(),event_type text NOT NULL CHECK(event_type IN('declared','note','action','escalation','resolved')),actor_id uuid REFERENCES auth.users(id),content text NOT NULL);
-- alert_rules is not present in the current database, so rule_id remains an opaque UUID until OBSERVE provisions its rule table.
CREATE TABLE IF NOT EXISTS public.runbook_alerts (id bigserial PRIMARY KEY,rule_id uuid,org_id uuid REFERENCES public.organizations(id),severity text,status text NOT NULL DEFAULT 'firing' CHECK(status IN('firing','acknowledged','resolved')),fired_at timestamptz NOT NULL DEFAULT now(),acknowledged_at timestamptz,acknowledged_by uuid REFERENCES auth.users(id),incident_id uuid REFERENCES public.runbook_incidents(id));

CREATE TABLE IF NOT EXISTS public.legal_holds (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),entity_type text NOT NULL,entity_id text,created_at timestamptz NOT NULL DEFAULT now());

ALTER TABLE public.privacy_consents ENABLE ROW LEVEL SECURITY; ALTER TABLE public.privacy_dsar_requests ENABLE ROW LEVEL SECURITY; ALTER TABLE public.privacy_erasure_jobs ENABLE ROW LEVEL SECURITY; ALTER TABLE public.trust_signals ENABLE ROW LEVEL SECURITY; ALTER TABLE public.trust_risk_profiles ENABLE ROW LEVEL SECURITY; ALTER TABLE public.trust_content_reports ENABLE ROW LEVEL SECURITY; ALTER TABLE public.finops_cost_events ENABLE ROW LEVEL SECURITY; ALTER TABLE public.finops_tenant_profitability ENABLE ROW LEVEL SECURITY; ALTER TABLE public.finops_anomalies ENABLE ROW LEVEL SECURITY; ALTER TABLE public.runbook_teams ENABLE ROW LEVEL SECURITY; ALTER TABLE public.runbook_schedules ENABLE ROW LEVEL SECURITY; ALTER TABLE public.runbook_incidents ENABLE ROW LEVEL SECURITY; ALTER TABLE public.runbook_timeline ENABLE ROW LEVEL SECURITY; ALTER TABLE public.runbook_alerts ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS privacy_consents_self ON public.privacy_consents; CREATE POLICY privacy_consents_self ON public.privacy_consents FOR SELECT TO authenticated USING(user_id=(select auth.uid()));
DROP POLICY IF EXISTS privacy_dsar_self ON public.privacy_dsar_requests; CREATE POLICY privacy_dsar_self ON public.privacy_dsar_requests FOR SELECT TO authenticated USING(user_id=(select auth.uid()));
DROP POLICY IF EXISTS privacy_erasure_self ON public.privacy_erasure_jobs; CREATE POLICY privacy_erasure_self ON public.privacy_erasure_jobs FOR SELECT TO authenticated USING(user_id=(select auth.uid()));
DROP POLICY IF EXISTS trust_profile_self ON public.trust_risk_profiles; CREATE POLICY trust_profile_self ON public.trust_risk_profiles FOR SELECT TO authenticated USING(user_id=(select auth.uid()));
DROP POLICY IF EXISTS trust_signals_self ON public.trust_signals; CREATE POLICY trust_signals_self ON public.trust_signals FOR SELECT TO authenticated USING(user_id=(select auth.uid()));
DROP POLICY IF EXISTS finops_org_select ON public.finops_cost_events; CREATE POLICY finops_org_select ON public.finops_cost_events FOR SELECT TO authenticated USING(public.is_org_member(organization_id));
DROP POLICY IF EXISTS finops_profit_org_select ON public.finops_tenant_profitability; CREATE POLICY finops_profit_org_select ON public.finops_tenant_profitability FOR SELECT TO authenticated USING(public.is_org_member(organization_id));
DROP POLICY IF EXISTS finops_anomaly_org_select ON public.finops_anomalies; CREATE POLICY finops_anomaly_org_select ON public.finops_anomalies FOR SELECT TO authenticated USING(public.is_org_member(organization_id));
DROP POLICY IF EXISTS runbook_team_org_select ON public.runbook_teams; CREATE POLICY runbook_team_org_select ON public.runbook_teams FOR SELECT TO authenticated USING(public.is_org_member(organization_id));
DROP POLICY IF EXISTS runbook_incident_org_select ON public.runbook_incidents; CREATE POLICY runbook_incident_org_select ON public.runbook_incidents FOR SELECT TO authenticated USING(public.is_org_member(organization_id));
DROP POLICY IF EXISTS runbook_schedule_org_select ON public.runbook_schedules; CREATE POLICY runbook_schedule_org_select ON public.runbook_schedules FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM public.runbook_teams t WHERE t.id=team_id AND public.is_org_member(t.organization_id)));
DROP POLICY IF EXISTS runbook_timeline_org_select ON public.runbook_timeline; CREATE POLICY runbook_timeline_org_select ON public.runbook_timeline FOR SELECT TO authenticated USING(EXISTS(SELECT 1 FROM public.runbook_incidents i WHERE i.id=incident_id AND public.is_org_member(i.organization_id)));
DROP POLICY IF EXISTS runbook_alert_org_select ON public.runbook_alerts; CREATE POLICY runbook_alert_org_select ON public.runbook_alerts FOR SELECT TO authenticated USING(public.is_org_member(org_id));
DROP POLICY IF EXISTS trust_reports_member_select ON public.trust_content_reports; CREATE POLICY trust_reports_member_select ON public.trust_content_reports FOR SELECT TO authenticated USING(reporter_id=(select auth.uid()) OR reviewed_by=(select auth.uid()));
